import { LayoutTemplate } from "@/components/templates";
import type { GenericComponentType } from "@/model";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Cellar - Overview",
  description: "Generated by create next app",
};

const RootLayout: GenericComponentType = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutTemplate>{children}</LayoutTemplate>
      </body>
    </html>
  );
};

export default RootLayout;
export { metadata };
